<a href="https://colab.research.google.com/github/FadouaKhm/CSE-590---Spring-2021---Intro-to-ML-and-DL-Tutorials/blob/main/%5BIntro_to_ML%5DRegression_Wine_Quality_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Problem 1 (Regression)

### Load Training and Testing Data

In [ ]:
import pandas as pd
import numpy as np
train_data = pd.read_csv('datasets/regression/wine_train.csv')
train_data.head()

Unnamed: 0  fixed.acidity  volatile.acidity  citric.acid  residual.sugar  \
0        2288            6.7              0.17         0.37            2.00   
1        1136           10.4              0.52         0.45            2.00   
2        4883            8.0              0.34         0.25            6.40   
3        3166            7.5              0.19         0.49            1.80   
4        2230            7.0              0.23         0.42           18.05   

   chlorides  free.sulfur.dioxide  total.sulfur.dioxide  density    pH  \
0      0.039                 34.0                 125.0  0.99220  3.26   
1      0.080                  6.0                  13.0  0.99774  3.22   
2      0.035                 38.0                 103.0  0.99148  2.91   
3      0.055                 19.0                 110.0  0.99460  3.33   
4      0.050                 35.0                 144.0  0.99990  3.22   

   sulphates  alcohol  quality  
0       0.60     10.8        7  
1       0.76     11.4        6  
2       0.23     12.2        6  
3       0.44      9.9        5  
4       0.42      8.8        5

In [ ]:
test_data = pd.read_csv('datasets/regression/wine_test.csv')
test_data.head()

Unnamed: 0  fixed.acidity  volatile.acidity  citric.acid  residual.sugar  \
0        2605            5.8              0.36         0.26             3.3   
1         536            9.9              0.63         0.24             2.4   
2         534           10.0              0.48         0.24             2.7   
3         813            6.9              0.39         0.24             2.1   
4         219            7.8              0.53         0.33             2.4   

   chlorides  free.sulfur.dioxide  total.sulfur.dioxide  density    pH  \
0      0.038                 40.0                 153.0  0.99110  3.34   
1      0.077                  6.0                  33.0  0.99740  3.09   
2      0.102                 13.0                  32.0  1.00000  3.28   
3      0.102                  4.0                   7.0  0.99462  3.44   
4      0.080                 24.0                 144.0  0.99655  3.30   

   sulphates  alcohol  quality  
0       0.55     11.3        6  
1       0.57      9.4        5  
2       0.56     10.0        6  
3       0.58     11.4        4  
4       0.60      9.5        5

In [ ]:
X_train = train_data.iloc[:,1:12].values
y_train = train_data.iloc[:,12].values

X_test = test_data.iloc[:, 1:12].values
y_test = test_data.iloc[:,12].values

### View Data

In [ ]:
X_train

array([[ 6.7 ,  0.17,  0.37, ...,  3.26,  0.6 , 10.8 ],
       [10.4 ,  0.52,  0.45, ...,  3.22,  0.76, 11.4 ],
       [ 8.  ,  0.34,  0.25, ...,  2.91,  0.23, 12.2 ],
       ...,
       [ 6.7 ,  0.76,  0.02, ...,  3.55,  0.63,  9.95],
       [ 6.9 ,  0.26,  0.33, ...,  3.39,  0.38,  9.9 ],
       [ 9.2 ,  0.18,  0.49, ...,  3.04,  0.49,  9.8 ]])

In [ ]:
X_train.shape

(4872, 11)

In [ ]:
y_train

array([7, 6, 6, ..., 3, 5, 7], dtype=int64)

In [ ]:
y_train.shape

(4872,)

In [ ]:
X_test

array([[ 5.8 ,  0.36,  0.26, ...,  3.34,  0.55, 11.3 ],
       [ 9.9 ,  0.63,  0.24, ...,  3.09,  0.57,  9.4 ],
       [10.  ,  0.48,  0.24, ...,  3.28,  0.56, 10.  ],
       ...,
       [ 6.4 ,  0.12,  0.3 , ...,  3.01,  0.56, 11.7 ],
       [ 7.1 ,  0.31,  0.25, ...,  3.14,  0.4 ,  9.5 ],
       [ 9.9 ,  0.35,  0.41, ...,  3.21,  0.5 ,  9.5 ]])

In [ ]:
X_test.shape

(1625, 11)

In [ ]:
y_test

array([6, 5, 6, ..., 6, 5, 5], dtype=int64)

In [ ]:
y_test.shape

(1625,)

### KNN Regression Model

In [ ]:
from sklearn.neighbors import KNeighborsRegressor
reg = KNeighborsRegressor(n_neighbors=10)
reg.fit(X_train,y_train)

KNeighborsRegressor(n_neighbors=10)

In [ ]:
# result = reg.predict(X_train)
# test1 = np.round(result,0)
# test1

In [ ]:
# result = reg.predict(X_test)
# test2 = np.round(result,0)
# test2

In [ ]:
# reg.score(X_train,test1)

In [ ]:
# reg.score(X_test,test2)

In [ ]:
# y_pred = reg.predict(X_train)
# y_pred

In [ ]:
# y_pred_rounded = np.round(y_pred,0)
# y_pred_rounded

In [ ]:
# from sklearn.metrics import r2_score
# r2_score(y_train,y_pred_rounded)

In [ ]:
reg.score(X_train,y_train)

0.30817215046149093

In [ ]:
reg.score(X_test,y_test)

0.19952300264162315

### OLS Regression Model

In [ ]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(X_train,y_train)

LinearRegression()

In [ ]:
# result = lr.predict(X_train)
# test1 = np.round(result, 0)
# test1

In [ ]:
# result = lr.predict(X_test)
# test2 = np.round(result, 0)
# test2

In [ ]:
#lr.score(X_train,test1)

In [ ]:
#lr.score(X_test,test2)

In [ ]:
lr.coef_

array([ 6.56051841e-02, -1.31845988e+00, -1.27628521e-01,  4.13145088e-02,
       -1.62638469e-01,  5.86443061e-03, -2.48848975e-03, -4.85670283e+01,
        4.00902913e-01,  6.76769740e-01,  2.72929267e-01])

In [ ]:
lr.intercept_

49.523099947287776

In [ ]:
lr.score(X_train,y_train)

0.2760977537347612

In [ ]:
lr.score(X_test,y_test)

0.336735748793488

### Ridge Regression Model

In [ ]:
from sklearn.linear_model import Ridge
ridge = Ridge(alpha=1)
ridge.fit(X_train,y_train)

Ridge(alpha=1)

In [ ]:
# result = ridge.predict(X_train)
# test1 = np.round(result, 0)
# test1

In [ ]:
# result = ridge.predict(X_test)
# test2 = np.round(result, 0)
# test2

In [ ]:
#ridge.score(X_train,test1)

In [ ]:
#ridge.score(X_test,test2)

In [ ]:
ridge.score(X_train,y_train)

0.2742472943511054

In [ ]:
ridge.score(X_test,y_test)

0.3329106234571949

### Lasso Regression Model

In [ ]:
from sklearn.linear_model import Lasso
lasso = Lasso(alpha=0.0001, max_iter=100000)
lasso.fit(X_train,y_train)

Lasso(alpha=0.0001, max_iter=100000)

In [ ]:
# result = lasso.predict(X_train)
# test1 = np.round(result, 0)
# test1

In [ ]:
# result = lasso.predict(X_test)
# test2 = np.round(result, 0)
# test2

In [ ]:
#lasso.score(X_train,test1)

In [ ]:
#lasso.score(X_test,test2)

In [ ]:
np.sum(lasso.coef_ != 0)

10

In [ ]:
lasso.score(X_train,y_train)

0.2742320549926104

In [ ]:
lasso.score(X_test,y_test)

0.33285559352541216